AUGMENTATION: True
IMAGE_SIZE: [224, 224, 3] # as per VGG 16 model
BATCH_SIZE: 16
INCLUDE_TOP: False
EPOCHS: 1 # if we want to increase accuracy we should use at least 300,400 epochs and take more images
CLASSES: 2
WEIGHTS: imagenet
LEARNING_RATE: 0.01
